### ISSUE TITLE
Version 2.6.4 cannot download s3 bucket files on non-ec2 hosted nodes

### ISSUE THREAD

**Issue by martinisoft** [chef-cookbooks/aws#111]
There might have been a breaking change in the aws-sdk with regards to the `aws_s3_file` resource. If I run a recipe with 2.6.4 on a node that is not hosted in AWS, it does not converge with the following:

```
Recipe: go-remote-control::install
       * aws_s3_file[/var/cache/rcserver-1.1.0] action create

           ================================================================================
           Error executing action `create` on resource 'aws_s3_file[/var/cache/rcserver-1.1.0]'
           ================================================================================

           Errno::ETIMEDOUT
           ----------------
           Connection timed out - connect(2) for "169.254.169.254" port 80

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/aws/libraries/ec2.rb:83:in `query_instance_availability_zone'
           /tmp/kitchen/cache/cookbooks/aws/libraries/ec2.rb:51:in `instance_availability_zone'
           /tmp/kitchen/cache/cookbooks/aws/libraries/ec2.rb:63:in `create_aws_interface'
           /tmp/kitchen/cache/cookbooks/aws/libraries/s3.rb:9:in `s3'
           /tmp/kitchen/cache/cookbooks/aws/providers/s3_file.rb:33:in `do_s3_file'
           /tmp/kitchen/cache/cookbooks/aws/providers/s3_file.rb:9:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/go-remote-control/recipes/install.rb

            19: aws_s3_file artifact_path do
            20:   bucket "dnsimple-packages"
            21:   remote_path "travis-builds/go-remote-control/#{artifact}"
            22:   aws_access_key_id access_key
            23:   aws_secret_access_key secrey_key
            24:   action (Chef::Config[:solo] ? :create_if_missing : :create)
            25:   not_if { File.exist?(artifact_path) }
            26: end
            27:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/go-remote-control/recipes/install.rb:19:in `from_file'
```

As you can see, a small detail in the stack trace above, it appears a lookup is happening somewhere that is trying to use the internal `169.254.169.254` metadata endpoint. If I roll back to the older 2.5.0 version of this cookbook using the same exact provider, it works normally without issue.

**Comment by martinisoft** [comment]
Updated the title of this issue to be a bit more clear.

**Comment by ubiquitousthey** [comment]
There is a problem with the way credentials are created and passed to the aws-sdk library.  I will get a PR out for this soon.

**Comment by ubiquitousthey** [comment]
PR #115 fixes this issue

**Comment by michaelpjohnson** [comment]
Was this ever merged? I'm still experiencing the issue.

**Comment by JC1738** [comment]
Same, testing in vagrant will give  

Errno::ETIMEDOUT
           ----------------
           Connection timed out - connect(2) for "169.254.169.254" port 80

Using cookbook 2.6.5 for aws

**Comment by JC1738** [comment]
Additional update, I tried the change in PR#115 and that got me past the problem, however instead I got another problem.  It didn't error, but instead it succeeded but the actual file on disk was of size 0.  Using same file with aws 2.4.0 properly downloads.

**Comment by joshzitting** [comment]
Hey I am having the same issue... we found a workaround but this is surely something that needs fixed..


https://github.com/opscode-cookbooks/aws/issues/120

**Comment by martinisoft** [comment]
Hi @joshzitting is #120 related to the #115 issue too?

**Comment by joshzitting** [comment]
I dont think so... I just changed my aws version to 2.4.0 and it works now.. My issue was not really a region issue I dont think. It was an issue where 2.6.5 wont let you download an s3 file unless you are on ec2. (I think)

**Comment by martinisoft** [comment]
@joshzitting well mine is a region issue related in the fact it needs you to be on ec2 to look up the region since it queries the internal metadata for this information. The previous version could be given that information or it would default for you.

**Comment by ubiquitousthey** [comment]
I just updated PR #115 to fix this

**Comment by joshzitting** [comment]
awesome I will try to give it a try today and let you know what I find.

**Comment by adamenger** [comment]
Ran into this issue today. Is there a fix?

**Comment by scottcarter87** [comment]
Still not working in 2.7.2.  Confirmed that it does work if you downgrade to 2.4.0.

**Comment by muddman** [comment]
Same here, doesn't work for me in 2.7.2, reverting to 2.4.0 did work.

**Comment by tas50** [comment]
This should be fixed on master which will be released shortly as 2.8.0
